# Generated by Django 6.1.1 on 2026-09-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bundles', '0003_bundle_unique_bundle_per_buyer_timestamp'),
        ('marketplace', '0004_listing_pricerecommendation_transaction'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(fields=('category_name',), name='unique_category_name'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('seller', 'title', 'created_at'), name='unique_seller_listing_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='pricerecommendation',
            constraint=models.UniqueConstraint(fields=('listing', 'generated_at'), name='unique_recommendation_per_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('listing', 'buyer'), name='unique_transaction_per_buyer_listing'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email', 'username'), name='unique_email_username'),
        ),
    ]
