# Generated by Django 6.1.1 on 2026-09-07 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bundle',
            constraint=models.UniqueConstraint(fields=('buyer', 'created_at'), name='unique_bundle_per_buyer_timestamp'),
        ),
    ]
